name: loomus_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+8

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  get_it: ^7.2.0
  intl: ^0.17.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  device_info_plus: ^6.0.0
  flutter_platform_widgets: ^2.0.0
  image_picker: ^0.8.6
  expandable: ^5.0.1
  fluttertoast: ^8.0.9
  dio_logging_interceptor: ^1.0.1
  share: ^2.0.4
  rate_my_app: ^1.1.3
  percent_indicator: ^4.2.2
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.1.0
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  amplitude_flutter: ^3.11.0
  collection: ^1.16.0
  url_launcher: ^6.1.6
  video_player: ^2.4.7
  get: ^4.6.5
  lottie: ^1.4.3
  http: ^0.13.5
  wakelock: ^0.6.2
  universal_html: ^2.0.8
  youtube_explode_dart: ^1.12.1
  package_info_plus: ^3.0.1
  appsflyer_sdk: ^6.8.2
  app_tracking_transparency: ^2.0.3
  firebase_messaging: ^14.0.4
  overlay_support: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  very_good_analysis: ^3.1.0

flutter_icons:
  image_path: "assets/app-icon/loomus-logo.png"
  adaptive_icon_foreground: "assets/app-icon/loomus-android.png"
  android: true
  ios: false
  adaptive_icon_background: "#128C7E"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/apple-logo.png
    - assets/images/attach.fill.png
    - assets/images/checkbox.fill.png
    - assets/images/checkmark.fill.png
    - assets/images/chevron.down.png
    - assets/images/chevron.left.png
    - assets/images/chevron.right.png
    - assets/images/chevron.up.png
    - assets/images/circle.png
    - assets/images/download.png
    - assets/images/gear.png
    - assets/images/google-logo.png
    - assets/images/file.doc.png
    - assets/images/file.image.png
    - assets/images/file.pdf.png
    - assets/images/file.presentation.png
    - assets/images/file.sheets.png
    - assets/images/file.unknown.png
    - assets/images/file.video.png
    - assets/images/file.zip.png
    - assets/images/hand.wave.png
    - assets/images/homework.png
    - assets/images/hourglass.png
    - assets/images/launch.png
    - assets/images/lock.png
    - assets/images/loomus.png
    - assets/images/mappin.png
    - assets/images/onboarding.png
    - assets/images/paint.brush.png
    - assets/images/placeholder.png
    - assets/images/radio.selected.png
    - assets/images/round.outline.png
    - assets/images/share.png
    - assets/images/smiley.png
    - assets/images/student-question.png
    - assets/images/sun.png
    - assets/images/test.png
    - assets/images/thumbs-down.png
    - assets/images/thumbs-up.png
    - assets/images/translate.png
    - assets/images/user.placeholder.png
    - assets/images/xmark.circle.fill.png
    - assets/images/xmark.png
    - assets/lottie/forward_left.json
    - assets/lottie/forward_right.json
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700