// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9DzioghySzusfkuWmH0M2hgjDUQFWpys',
    appId: '1:304003122421:android:ffca09e512f418a5de31bc',
    messagingSenderId: '304003122421',
    projectId: 'zoolu-app',
    databaseURL: 'https://zoolu-app-default-rtdb.firebaseio.com',
    storageBucket: 'zoolu-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmU7rAJ_1fp93poPHxIXgbA0wLop3o-7A',
    appId: '1:304003122421:ios:2fe39708c5cf138ede31bc',
    messagingSenderId: '304003122421',
    projectId: 'zoolu-app',
    databaseURL: 'https://zoolu-app-default-rtdb.firebaseio.com',
    storageBucket: 'zoolu-app.appspot.com',
    androidClientId: '304003122421-5qivkfvl01nrtftqlfjodo59f0slctee.apps.googleusercontent.com',
    iosClientId: '304003122421-17fkntup1nmlnb8vbcl8b0b0issclb10.apps.googleusercontent.com',
    iosBundleId: 'io.loomus.loomusApp',
  );
}
